//
// main.cpp 
// Main file
// ----------------------------------
// Developed with embedXcode 
// http://embedXcode.weebly.com
//
// Project SketchTheEtch
//
// Created by Evan Long, 11/3/12 8:22 PM
// Hippo
//	
//
// Copyright © Evan Long, 2012
// Licence CC = BY NC SA
//
// See SketchTheEtch.pde and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN SketchTheEtch.pde
// ----------------------------------
//


// Core library - IDE-based
#if defined(WIRING) // Wiring specific - official
#include "Wiring.h"
#elif defined(MAPLE_IDE) // Maple specific - official
#include "WProgram.h"   
#elif defined(MPIDE) // chipKIT specific - embedXcode only
#include "WProgram.h"
#elif defined(ENERGIA) // LaunchPad specific - embedXcode only
#include "Energia.h"
#elif defined(ARDUINO) && (ARDUINO >= 100) // Arduino 1.0 specific - official
#include "Arduino.h"
#elif defined(ARDUINO) && (ARDUINO < 100) // Arduino 23 specific - official
#include "WProgram.h"
#else // error
#error Platform not defined
#endif


// Sketch
#include "SketchTheEtch.cpp"

int main(void)
{
#if defined(__AVR_ATmega644P__) // Wiring specific
  boardInit();
#else
  init();
  
#if defined(USBCON) // Arduino 1.0 specific
  USBDevice.attach();
#endif
  
#endif
  
  setup();
  for (;;) {
    
    loop();
    
#if defined(ARDUINO) && (ARDUINO >= 100) // Arduino 1.0 specific
    if (serialEventRun) serialEventRun();
#endif
  }
  
  return 0;
}
